@startuml
    :Consigliere della città: as CC
    :Capo consigliere: as HeadC

    :Centro operativo di sicurezza: as COS
    :Sistema di intelligence: as SI
    :Sindaco: as S

    :Ministero dell'innovazione tecnologica: as MIT
    :Direttore tecnico: as DT

    (Inviare comunicazioni di emergenza) as UC1
    (Convocare riunioni del consiglio) as UC2

    (Convocare riunioni con sindaco) as UC3
    (Rilascio autorizzazione) as RA

    usecase UC4 as "
        Monitora città in tempo reale
        --
        E.P.:
         - Minaccia rilevata
    "
    (Attiva protocollo di difesa) as UC5
    (Conferma) as UC6
    (Dichiara stato di emmergenza) as UC7
    (Autorizzazione del sindaco) as UC8

    (Gestire le squadre di manutenzione) as UC9
    (Aggiorna software) as UC10
    (Tracciamento operazioni) as UC11

    (Autorizzare modifiche) as UC12

    CC -- UC1
    CC -- UC2

    HeadC --|> CC

    HeadC --> UC3
    UC3 ..> RA : <<include>>
    S -- UC3

    COS -- UC4
    UC5 .up.> UC4 : <<extend>>
    SI -- UC4
    UC5 ..> UC6 : <<include>>
    COS --> UC7
    UC7 ..> UC8 : <<include>>
    S -- UC8

    MIT -- UC9
    MIT -- UC10
    UC9 ..> UC11 : <<include>>
    UC10 ..> UC11 : <<include>>

    DT --|> MIT
    DT -- UC12

@enduml